@echo off
echo Creating 'Blue' Directory...
mkdir Blue
echo Unzipping 'team\editor\dist\Blue-win32-x64.zip'...
tar -xf team\editor\dist\Blue-win32-x64.zip -C Blue\
echo Starting Blue GUI...
Blue\Blue.exe
@pause